#.gitlab-ci.yml
#GitLab CI/CD-fil som (bland annat) automatiserar uppladdningen av själva gränsnittet till webbservern.
update-website-job:
  stage: deploy
  image: node:alpine
  before_script:
    #Installera saker som vi behöver
    - apk add git
    - apk add openssh
    - apk add --no-cache lftp
    - apk add sshpass
    - apk add lftp
  script:
    #Lägg till hem.ssis.nu till listan med kända värdnamn
    - mkdir /root/.ssh                                
    - chmod 700 /root/.ssh                            
    - touch /root/.ssh/known_hosts                  
    - chmod 600 /root/.ssh/known_hosts                
    - ssh-keyscan -H hem.ssis.nu >> /root/.ssh/known_hosts
    #Flytta in i den mapp vi vill
    - cd frontend/yatzyprojekt
    #Skriv ut lite debugging
    - echo "[DEBUGGING!] Debug - mappinnehåll:"
    - ls
    #Pusha hemsidesinnehåll
    - echo "[PÅ G!] Installerar dependecies..."
    - npm install
    - echo "[PÅ G!] Bygger hemsidan..."
    - npm run build
    - cd dist
    - echo "[DEBUGGING!] Debug - byggt innehåll:"
    - ls
    - echo "[PÅ G!] Pushar hemsidan till hem.ssis.nu..."
    - echo "[PÅ G!] Laddar upp till server..."
    - lftp -e "mirror -e -P 4 -R --transfer-all --reverse -X README.md -X .gitignore -X .gitlab-ci.yml -X .vscode/ -X .git/ . /public_html/yatzy/ --verbose; quit" -u "$SFTP_USERNAME,$SFTP_PASSWORD" sftp://hem.ssis.nu -p 22
    - echo "[YAY! KLAR!] Hemsidan uppladdad!"
  timeout: 2min