apiVersion: v1
data:
  MYSQL_DATABASE: db
  MYSQL_PASSWORD: ""
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_USER: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-mysql_server-env
  name: mysql_server-env
